name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
        - name: Docker Login
          uses: docker/login-action@v3.3.0
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Set docker tag
          run: echo "DOCKER_TAG=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

        - name: Build and push Docker images
          uses: docker/build-push-action@v6.7.0
          with:
            dockerfile: Dockerfile
            push: true
            tags: ghcr.io/${{ env.DOCKER_TAG }}:latest
